name: MacOS ARM

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos-arm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Git Submodule Update
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: >
        cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=Release
        -DBUILD_ARM=ON
        -S ${{github.workspace}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose

    - name: Run Application
      working-directory: ${{github.workspace}}/build
      run: ./bin/vscit
